version: "3.8"

services:
  flatnotes:
    image: dullage/flatnotes:latest
    container_name: flatnotes
    restart: unless-stopped
    ports:
      - "${FLATNOTES_PORT}:8080"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - FLATNOTES_AUTH_TYPE=${FLATNOTES_AUTH_TYPE}
      - FLATNOTES_USERNAME=${FLATNOTES_USERNAME}
      - FLATNOTES_PASSWORD=${FLATNOTES_PASSWORD}
      - FLATNOTES_SECRET_KEY=${FLATNOTES_SECRET_KEY}
    volumes:
      - ./data:/data
    networks:
      - common-net

networks:
  common-net:
    external: true