version: "3.8"

services:
  backend:
    image: caddymanager/caddymanager-backend:latest
    container_name: caddymanager-backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=sqlite:///data/database.db
      - CADDY_API_URL=http://caddy:2019
      - CADDY_API_KEY=${CADDY_API_KEY}
    volumes:
      - ./data:/data
    networks:
      - common-net

  frontend:
    image: caddymanager/caddymanager-frontend:latest
    container_name: caddymanager-frontend
    restart: unless-stopped
    ports:
      - "${CADDYMANAGER_PORT}:80"
    environment:
      - VITE_API_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - common-net

networks:
  common-net:
    external: true